### ISSUE TITLE
https only

### ISSUE THREAD

**Issue by mmBesar** [KevinCFechtel/FluxNews#18]
I found the app on F-Droid today, but it wont accept my http api url, when I add https, it was accepted!
Please let it accept http urls.
Thanks.

**Comment by KevinCFechtel** [comment]
Hello, 
is the miniflux server in the private network or is it accessible from the Internet?
Since Android version 9, http connections to servers outside the local network are prohibited by default.
The app would therefore have to explicitly request permission for insecure connections and would therefore tend to behave insecurely.
In addition, the API key would be readable with every request to the miniflux server.
I would like to prevent this risk in the standard.
Is it therefore really not possible to reach the miniflux server with an https connection?

**Comment by mmBesar** [comment]
I have a simple local and personal setup, not facing the internet. I can access the server without any problem via [miniflutt](https://github.com/DocMarty84/miniflutt) and [News](https://github.com/bubelov/news) from the local network, or over Tailscale.
Kindly allow `http` with a clear warning for users.
Looking forward to trying the app, thanks.

**Comment by KevinCFechtel** [comment]
OK, then I will remove the internal restriction to HTTPS, but not yet request authorization for http traffic to the outside.
As far as I understand it, this should be sufficient for local servers. I'll let you know as soon as the new release is ready.

**Comment by mmBesar** [comment]
I'll be eagerly waiting, thank you.

**Comment by KevinCFechtel** [comment]
I have just published a new release with support for insecure http connections.
It will probably take 1-3 days until this release is available in the f-droid store.
Please test if the http connection with the local server works, unfortunately I don't have a local miniflux instance to test this.

**Comment by mmBesar** [comment]
I'll report back as soon as it is published.
Thanks.

**Comment by KevinCFechtel** [comment]
Hello, I wanted to ask if the unencrypted http connections to the local server are now working? The update should be available by now.

**Comment by mmBesar** [comment]
Just checked, and it is working, thank you.
I hope to see an offline reading soon.
Thanks again.
