### ISSUE TITLE
Add swipe actions to overview

### ISSUE THREAD

**Issue by aflox405** [KevinCFechtel/FluxNews#55]
It would be nice if on the overview page we could use swiping instead of long pressing the item to do certain actions, eg. Swipe right to mark as read and swipe left to save to third party.

**Comment by KevinCFechtel** [comment]
Thanks for the idea, I'll have a look.

**Comment by KevinCFechtel** [comment]
Would it be OK if the action was not executed immediately after the swipe, but if there were still actions that could then be triggered with a separate touch?
Something like this:
![image](https://raw.githubusercontent.com/letsar/flutter_slidable/assets/behind_motion.gif)

I would prefer this so that a swipe does not accidentally lead to an action.

**Comment by KevinCFechtel** [comment]
I will post a new release today which will provide the swipe actions.
There will be one action per Swipe side, which can be defined in the settings. 
If you only swipe to the right or left briefly, the action is displayed as a button, after a tap on the button the action is executed. 
If you swipe further to the right or left, the configured action is executed directly without having to tap it again.
Thanks for the tip, this is a cool new feature.
