### ISSUE TITLE
Error occurred while processing the data

### ISSUE THREAD

**Issue by snauth** [KevinCFechtel/FluxNews#60]
Since a couple of weeks (not sure if it was after an update) I get an error when syncing ("Error occurred while processing the data"). The news counts are updated but the app window remains empty. If I clear local news storage, mark all news read in the miniflux webapp and start miniflux anew it works for a while but then the error comes back.

```
{FluxNews}  {fetchNews}  {Finished fetching news from miniflux server}  {30 August 2024 02:35:48 PM}  {INFO}
{FluxNews}  {markNotFetchedNewsAsRead}  {Starting marking not fetched news as read}  {30 August 2024 02:35:48 PM}  {INFO}
{FluxNews}  {markNotFetchedNewsAsRead}  {Caught an error in markNotFetchedNewsAsRead function! : DatabaseException(Row too big to fit into CursorWindow requiredPos=9, totalRows=10) sql 'SELECT * FROM news WHERE status = ? AND syncStatus = ?' args [unread, notSynced]}  {30 August 2024 02:35:48 PM}  {ERROR}
{FluxNews}  {fetchCategoryInformation}  {Starting fetching category information from miniflux server}  {30 August 2024 02:35:48 PM}  {INFO}
{FluxNews}  {fetchCategoryInformation}  {Finished fetching category information from miniflux server}  {30 August 2024 02:35:49 PM}  {INFO}
{FluxNews}  {insertCategoriesInDB}  {Starting inserting categories in DB}  {30 August 2024 02:35:49 PM}  {INFO}
{FluxNews}  {insertCategoriesInDB}  {Updated category with id 1 in DB}  {30 August 2024 02:35:49 PM}  {INFO}
{FluxNews}  {insertCategoriesInDB}  {Updated feed with id 2 in DB}  {30 August 2024 02:35:49 PM}  {INFO}
{FluxNews}  {insertCategoriesInDB}  {Updated feed with id 7 in DB}  {30 August 2024 02:35:49 PM}  {INFO}
```

```
{FluxNews}  {syncNews}  {Start syncing with miniflux server.}  {01 September 2024 09:08:55 PM}  {INFO}
{FluxNews}  {markNotFetchedNewsAsRead}  {Caught an error in markNotFetchedNewsAsRead function! : DatabaseException(Row too big to fit into CursorWindow requiredPos=112, totalRows=113) sql 'SELECT * FROM news WHERE status = ? AND syncStatus = ?' args [unread, notSynced]}  {01 September 2024 09:08:56 PM}  {ERROR}
{FluxNews}  {insertNewsInDB}  {Caught an error in insertNewsInDB function! : DatabaseException(Row too big to fit into CursorWindow requiredPos=0, totalRows=1) sql 'SELECT * FROM news WHERE newsID = ?' args [10565]}  {01 September 2024 09:08:57 PM}  {ERROR}
{FluxNews}  {syncNews}  {Finished syncing with miniflux server.}  {01 September 2024 09:08:57 PM}  {INFO}
```

Miniflux version 2.2.0
Flux News version 1.5.5

**Comment by KevinCFechtel** [comment]
At first glance, it looks like there are news items that contain too much data to be read out of the SQLite database. 
The problem already existed once with feed icons that were too large for the database (so they are no longer stored in the database), but this time it seems to be the news itself that is too large. 
I assume that the entries from miniflux have a lot of content? 
I guess I can't solve the problem in general, but I will add a quantity limit when reading the content from the SQLite database to work around the problem. 
This means that there will be entries with shortened content. 
Unfortunately, I won't be able to implement this this week, but I hope to be able to do it this weekend. I'll let you know as soon as I have something to test, it would be great if you could install the app once via the PlayStore, because I can give you access to a beta test so that we can get a result quickly. 
Alternatively, you could give me your feeds and I would see which feed produces the amount of data and then test it myself locally.

**Comment by snauth** [comment]
Shortened content would be no problem. Unfortunately I have no access to the play store (ungoogled phone) but my feeds are here: 
https://nextcloud.kultwiki.net/s/Ne3jT9b6R5nbxTZ/download/feeds.opml

**Comment by KevinCFechtel** [comment]
Thanks, I've set up the feeds on a test instance and will see if I can find an entry to reproduce the error.

**Comment by snauth** [comment]
Please wait with debugging, I am currently testing the theory that an url rewrite rule on the miniflux side has caused the errors. I will close the issue if my theory is confirmed.

**Comment by snauth** [comment]
Not sure what the url rewrite did in some edge cases but without it the error seems to have gone away.
